
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { KeyboardAvoidingView, Component } from 'react';
import { TabNavigator, StackNavigator } from 'react-navigation';
import {StyleSheet} from 'react-native';
import Main from './Main.js'
import ExperimentBrowse from './ExperimentBrowse.js'
import HomePage from './HomePage.js'
import { AppRegistry, ScrollView, View} from 'react-native';
import TabBar from '../components/TabBar/TabBar.js'
import UserProfile from "./UserProfile";
import Experiment from './Experiment.js'
import BackgroundGeolocation from 'react-native-mauron85-background-geolocation';
import ChooseAddress from './ChooseAddress'
import ExperimentComplete from './ExperimentComplete'
import PushNotification from 'react-native-push-notification'

export default class App extends Component<{}> {

    componentWillMount()
    {
        //Register to push notifications
        PushNotification.configure({

            // (optional) Called when Token is generated (iOS and Android)
            onRegister: function(token) {
                console.log( 'TOKEN:', token );
            },

            // (required) Called when a remote or local notification is opened or received
            onNotification: function(notification) {
                console.log( 'NOTIFICATION:', notification );
                // process the notification

                // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
               // notification.finish(PushNotificationIOS.FetchResult.NoData);
            },

            // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
            senderID: "YOUR GCM SENDER ID",

            // IOS ONLY (optional): default: all - Permissions to register.
            permissions: {
                alert: true,
                badge: true,
                sound: true
            },

            // Should the initial notification be popped automatically
            // default: true
            popInitialNotification: true,

            /**
             * (optional) default: true
             * - Specified if permissions (ios) and token (android and ios) will requested or not,
             * - if not, you must call PushNotificationsHandler.requestPermissions() later
             */
            requestPermissions: true,
        });

        BackgroundGeolocation.configure({
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 50,
            startForeground:false,
            debug: false,
            startOnBoot: false,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 5000,
            fastestInterval: 1000,
            activitiesInterval: 100,
            stopOnStillActivity: false,
            url: 'http://192.168.81.15:3000/location',
            /*httpHeaders: {
                'X-FOO': 'bar'
            }*/
        });

        console.log("App.js called");

        PushNotification.localNotification({
            /* Android Only Properties */
          // id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
         //   ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: false, // (optional) default: true
            vibration: 3000, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
          //  group: "group", // (optional) add group to message
            //ongoing: false, // (optional) set whether this is an "ongoing" notification

        //    /* iOS only properties */
        //     alertAction: // (optional) default: view
        //     category: // (optional) default: null
        // userInfo: // (optional) default: null (object containing additional notification data)

            /* iOS and Android properties */
            title: "Test Source", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
                message: "My Notification Message", // (required)
            playSound: true, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
          //  number: '1', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
           // repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
          //  actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
        });

        BackgroundGeolocation.on('location', (location) => {
            // handle your locations here
            // to perform long running operation on iOS
            // you need to create background task
            console.log("BackgroundGeolocation (Active)" + JSON.stringify(location));

            //if(locatio)

            //Check if they've completed today
            //Check if they've been notified about completing today within the past 2 hours

            BackgroundGeolocation.startTask(taskKey => {
                // execute long running task
                // eg. ajax post location
                // IMPORTANT: task has to be ended by endTask
                BackgroundGeolocation.endTask(taskKey);
            });
        });

        BackgroundGeolocation.on('stationary', (stationaryLocation) => {
            // handle stationary locations here
            //Actions.sendLocation(stationaryLocation);
            console.log("BackgroundGeolocation (Stationary) " + JSON.stringify(stationaryLocation));
        });

        BackgroundGeolocation.on('error', (error) => {
            console.log('[ERROR] BackgroundGeolocation error:', error);
        });

        BackgroundGeolocation.on('start', () => {
            console.log('[INFO] BackgroundGeolocation service has been started');
        });

        BackgroundGeolocation.on('stop', () => {
            console.log('[INFO] BackgroundGeolocation service has been stopped');
        });

        BackgroundGeolocation.on('authorization', (status) => {
            console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
            if (status !== BackgroundGeolocation.AUTHORIZED) {
                Alert.alert('Location services are disabled', 'Would you like to open location settings?', [
                    { text: 'Yes', onPress: () => BackgroundGeolocation.showLocationSettings() },
                    { text: 'No', onPress: () => console.log('No Pressed'), style: 'cancel' }
                ]);
            }
        });

        BackgroundGeolocation.on('background', () => {
            console.log('[INFO] App is in background');
        });

        BackgroundGeolocation.on('foreground', () => {
            console.log('[INFO] App is in foreground');
        });

        BackgroundGeolocation.checkStatus(status => {
            console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
            console.log('[INFO] BackgroundGeolocation service has permissions', status.hasPermissions);
            console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);

            // you don't need to check status before start (this is just the example)
            if (!status.isRunning) {
                BackgroundGeolocation.start(); //triggers start on start event
            }
        });
    }

    componentWillUnmount() {
        // unregister all event listeners
        BackgroundGeolocation.events.forEach(event => BackgroundGeolocation.removeAllListeners(event));
    }

    render() {
        return (
            <RootNavigator />
        )}
}

var navigationBarStyles = StyleSheet.create({
    navigationBar: {
        backgroundColor: '#FFFFFF',
        height: 30,
        position: 'absolute',
        flexDirection: 'row',
        bottom: 0,
        justifyContent: 'space-between'
    },
});

const RootNavigator =
    StackNavigator(
        {
            SignIn: {
                screen: Main,
            },
            ChooseAddress:
            {
                screen: ChooseAddress,
            },
            ExperimentComplete:
            {
                screen: ExperimentComplete,
            },
            Authenticated: {
                screen:
                    TabNavigator({
                        HomePage: {
                            screen: HomePage,
                        },
                        ExperimentBrowse: {
                            screen:
                                StackNavigator({
                                        ExperimentBrowse: {
                                            screen: ExperimentBrowse
                                        },
                                        Experiment: {
                                            screen: Experiment
                                        }
                                    },
                                    {
                                        headerMode: "none"
                                    })
                        },
                        UserProfile: {
                            screen: UserProfile
                        },
                    },
                    {
                        tabBarComponent: TabBar,
                        headerMode: 'none',
                        tabBarPosition: 'bottom',
                    })
            }
        },
        {
            headerMode:'none'
        });
//AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

//() => (<LoginForm SignUp={true}}/>) how to pass props
